function djuqbox(){var O='bootstrap',P='begin',Q='gwt.codesvr.djuqbox=',R='gwt.codesvr=',S='djuqbox',T='startup',U='DUMMY',V=0,W=1,X='iframe',Y='javascript:""',Z='position:absolute; width:0; height:0; border:none; left: -1000px;',$=' top: -1000px;',_='CSS1Compat',ab='<!doctype html>',bb='',cb='<html><head><\/head><body><\/body><\/html>',db='undefined',eb='DOMContentLoaded',fb=50,gb='Chrome',hb='eval("',ib='");',jb='script',kb='javascript',lb='moduleStartup',mb='moduleRequested',nb='Failed to load ',ob='head',pb='meta',qb='name',rb='djuqbox::',sb='::',tb='gwt:property',ub='content',vb='=',wb='gwt:onPropertyErrorFn',xb='Bad handler "',yb='" for "gwt:onPropertyErrorFn"',zb='gwt:onLoadErrorFn',Ab='" for "gwt:onLoadErrorFn"',Bb='#',Cb='?',Db='/',Eb='img',Fb='clear.cache.gif',Gb='baseUrl',Hb='djuqbox.nocache.js',Ib='base',Jb='//',Kb='bstplayer.platform',Lb='linux',Mb='mac',Nb='other',Ob='win',Pb=2,Qb=3,Rb='user.agent',Sb='webkit',Tb='safari',Ub='msie',Vb=10,Wb=11,Xb='ie10',Yb=9,Zb='ie9',$b=8,_b='ie8',ac='gecko',bc='gecko1_8',cc=4,dc='selectingPermutation',ec='djuqbox.devmode.js',fc='3A874A13ED30D49CFD4F060B823F9AB8',gc=':1',hc=':2',ic=':3',jc='4C86C65F2E82E7E1099CEE464871B0E8',kc='7C2275EC75196EF52FB82B2CF90BDD2D',lc='C08631215DF5CFF3409BED84E0C5A2E9',mc='F7C1219D58A7B54D52CE15D192E7B1B6',nc=':',oc='.cache.js',pc='link',qc='rel',rc='stylesheet',sc='href',tc='loadExternalRefs',uc='gwt/dark/dark.css',vc='custom-control-styles.css',wc='end',xc='http:',yc='file:',zc='_gwt_dummy_',Ac='__gwtDevModeHook:djuqbox',Bc='Ignoring non-whitelisted Dev Mode URL: ',Cc=':moduleBase';var o=window;var p=document;r(O,P);function q(){var a=o.location.search;return a.indexOf(Q)!=-1||a.indexOf(R)!=-1}
function r(a,b){if(o.__gwtStatsEvent){o.__gwtStatsEvent({moduleName:S,sessionId:o.__gwtStatsSessionId,subSystem:T,evtGroup:a,millis:(new Date).getTime(),type:b})}}
djuqbox.__sendStats=r;djuqbox.__moduleName=S;djuqbox.__errFn=null;djuqbox.__moduleBase=U;djuqbox.__softPermutationId=V;djuqbox.__computePropValue=null;djuqbox.__getPropMap=null;djuqbox.__installRunAsyncCode=function(){};djuqbox.__gwtStartLoadingFragment=function(){return null};djuqbox.__gwt_isKnownPropertyValue=function(){return false};djuqbox.__gwt_getMetaProperty=function(){return null};var s=null;var t=o.__gwt_activeModules=o.__gwt_activeModules||{};t[S]={moduleName:S};djuqbox.__moduleStartupDone=function(e){var f=t[S].bindings;t[S].bindings=function(){var a=f?f():{};var b=e[djuqbox.__softPermutationId];for(var c=V;c<b.length;c++){var d=b[c];a[d[V]]=d[W]}return a}};var u;function v(){w();return u}
function w(){if(u){return}var a=p.createElement(X);a.src=Y;a.id=S;a.style.cssText=Z+$;a.tabIndex=-1;p.body.appendChild(a);u=a.contentDocument;if(!u){u=a.contentWindow.document}u.open();var b=document.compatMode==_?ab:bb;u.write(b+cb);u.close()}
function A(k){function l(a){function b(){if(typeof p.readyState==db){return typeof p.body!=db&&p.body!=null}return /loaded|complete/.test(p.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(p.removeEventListener){p.removeEventListener(eb,d,false)}if(e){clearInterval(e)}}}
if(p.addEventListener){p.addEventListener(eb,d,false)}var e=setInterval(function(){if(b()){d()}},fb)}
function m(c){function d(a,b){a.removeChild(b)}
var e=v();var f=e.body;var g;if(navigator.userAgent.indexOf(gb)>-1&&window.JSON){var h=e.createDocumentFragment();h.appendChild(e.createTextNode(hb));for(var i=V;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(e.createTextNode(j.substring(W,j.length-W)))}h.appendChild(e.createTextNode(ib));g=e.createElement(jb);g.language=kb;g.appendChild(h);f.appendChild(g);d(f,g)}else{for(var i=V;i<c.length;i++){g=e.createElement(jb);g.language=kb;g.text=c[i];f.appendChild(g);d(f,g)}}}
djuqbox.onScriptDownloaded=function(a){l(function(){m(a)})};r(lb,mb);var n=p.createElement(jb);n.src=k;if(djuqbox.__errFn){n.onerror=function(){djuqbox.__errFn(S,new Error(nb+code))}}p.getElementsByTagName(ob)[V].appendChild(n)}
djuqbox.__startLoadingFragment=function(a){return D(a)};djuqbox.__installRunAsyncCode=function(a){var b=v();var c=b.body;var d=b.createElement(jb);d.language=kb;d.text=a;c.appendChild(d);c.removeChild(d)};function B(){var c={};var d;var e;var f=p.getElementsByTagName(pb);for(var g=V,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(qb),k;if(j){j=j.replace(rb,bb);if(j.indexOf(sb)>=V){continue}if(j==tb){k=i.getAttribute(ub);if(k){var l,m=k.indexOf(vb);if(m>=V){j=k.substring(V,m);l=k.substring(m+W)}else{j=k;l=bb}c[j]=l}}else if(j==wb){k=i.getAttribute(ub);if(k){try{d=eval(k)}catch(a){alert(xb+k+yb)}}}else if(j==zb){k=i.getAttribute(ub);if(k){try{e=eval(k)}catch(a){alert(xb+k+Ab)}}}}}__gwt_getMetaProperty=function(a){var b=c[a];return b==null?null:b};s=d;djuqbox.__errFn=e}
function C(){function e(a){var b=a.lastIndexOf(Bb);if(b==-1){b=a.length}var c=a.indexOf(Cb);if(c==-1){c=a.length}var d=a.lastIndexOf(Db,Math.min(c,b));return d>=V?a.substring(V,d+W):bb}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=p.createElement(Eb);b.src=a+Fb;a=e(b.src)}return a}
function g(){var a=__gwt_getMetaProperty(Gb);if(a!=null){return a}return bb}
function h(){var a=p.getElementsByTagName(jb);for(var b=V;b<a.length;++b){if(a[b].src.indexOf(Hb)!=-1){return e(a[b].src)}}return bb}
function i(){var a=p.getElementsByTagName(Ib);if(a.length>V){return a[a.length-W].href}return bb}
function j(){var a=p.location;return a.href==a.protocol+Jb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==bb){k=h()}if(k==bb){k=i()}if(k==bb&&j()){k=e(p.location.href)}k=f(k);return k}
function D(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return djuqbox.__moduleBase+a}
function F(){var f=[];var g=V;function h(a,b){var c=f;for(var d=V,e=a.length-W;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var i=[];var j=[];function k(a){var b=j[a](),c=i[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(s){s(a,d,b)}throw null}
j[Kb]=function(){var a=navigator.platform.toLowerCase();if(a.indexOf(Lb)!=-1){return Lb}else if(a.indexOf(Mb)!=-1){return Mb}else if(a.indexOf(Nb)!=-1){return Nb}else if(a.indexOf(Ob)!=-1){return Ob}else{return Nb}};i[Kb]={linux:V,mac:W,other:Pb,win:Qb};j[Rb]=function(){var a=navigator.userAgent.toLowerCase();var b=p.documentMode;if(function(){return a.indexOf(Sb)!=-1}())return Tb;if(function(){return a.indexOf(Ub)!=-1&&(b>=Vb&&b<Wb)}())return Xb;if(function(){return a.indexOf(Ub)!=-1&&(b>=Yb&&b<Wb)}())return Zb;if(function(){return a.indexOf(Ub)!=-1&&(b>=$b&&b<Wb)}())return _b;if(function(){return a.indexOf(ac)!=-1||b>=Wb}())return bc;return bb};i[Rb]={gecko1_8:V,ie10:W,ie8:Pb,ie9:Qb,safari:cc};__gwt_isKnownPropertyValue=function(a,b){return b in i[a]};djuqbox.__getPropMap=function(){var a={};for(var b in i){if(i.hasOwnProperty(b)){a[b]=k(b)}}return a};djuqbox.__computePropValue=k;o.__gwt_activeModules[S].bindings=djuqbox.__getPropMap;r(O,dc);if(q()){return D(ec)}var l;try{h([Lb,Tb],fc);h([Mb,Tb],fc);h([Nb,Tb],fc);h([Ob,Tb],fc);h([Lb,Tb],fc+gc);h([Mb,Tb],fc+gc);h([Nb,Tb],fc+gc);h([Ob,Tb],fc+gc);h([Lb,Tb],fc+hc);h([Mb,Tb],fc+hc);h([Nb,Tb],fc+hc);h([Ob,Tb],fc+hc);h([Lb,Tb],fc+ic);h([Mb,Tb],fc+ic);h([Nb,Tb],fc+ic);h([Ob,Tb],fc+ic);h([Lb,Zb],jc);h([Mb,Zb],jc);h([Nb,Zb],jc);h([Ob,Zb],jc);h([Lb,Zb],jc+gc);h([Mb,Zb],jc+gc);h([Nb,Zb],jc+gc);h([Ob,Zb],jc+gc);h([Lb,Zb],jc+hc);h([Mb,Zb],jc+hc);h([Nb,Zb],jc+hc);h([Ob,Zb],jc+hc);h([Lb,Zb],jc+ic);h([Mb,Zb],jc+ic);h([Nb,Zb],jc+ic);h([Ob,Zb],jc+ic);h([Lb,_b],kc);h([Mb,_b],kc);h([Nb,_b],kc);h([Ob,_b],kc);h([Lb,_b],kc+gc);h([Mb,_b],kc+gc);h([Nb,_b],kc+gc);h([Ob,_b],kc+gc);h([Lb,_b],kc+hc);h([Mb,_b],kc+hc);h([Nb,_b],kc+hc);h([Ob,_b],kc+hc);h([Lb,_b],kc+ic);h([Mb,_b],kc+ic);h([Nb,_b],kc+ic);h([Ob,_b],kc+ic);h([Lb,bc],lc);h([Mb,bc],lc);h([Nb,bc],lc);h([Ob,bc],lc);h([Lb,bc],lc+gc);h([Mb,bc],lc+gc);h([Nb,bc],lc+gc);h([Ob,bc],lc+gc);h([Lb,bc],lc+hc);h([Mb,bc],lc+hc);h([Nb,bc],lc+hc);h([Ob,bc],lc+hc);h([Lb,bc],lc+ic);h([Mb,bc],lc+ic);h([Nb,bc],lc+ic);h([Ob,bc],lc+ic);h([Lb,Xb],mc);h([Mb,Xb],mc);h([Nb,Xb],mc);h([Ob,Xb],mc);h([Lb,Xb],mc+gc);h([Mb,Xb],mc+gc);h([Nb,Xb],mc+gc);h([Ob,Xb],mc+gc);h([Lb,Xb],mc+hc);h([Mb,Xb],mc+hc);h([Nb,Xb],mc+hc);h([Ob,Xb],mc+hc);h([Lb,Xb],mc+ic);h([Mb,Xb],mc+ic);h([Nb,Xb],mc+ic);h([Ob,Xb],mc+ic);l=f[k(Kb)][k(Rb)];var m=l.indexOf(nc);if(m!=-1){g=parseInt(l.substring(m+W),Vb);l=l.substring(V,m)}}catch(a){}djuqbox.__softPermutationId=g;return D(l+oc)}
function G(){if(!o.__gwt_stylesLoaded){o.__gwt_stylesLoaded={}}function c(a){if(!__gwt_stylesLoaded[a]){var b=p.createElement(pc);b.setAttribute(qc,rc);b.setAttribute(sc,D(a));p.getElementsByTagName(ob)[V].appendChild(b);__gwt_stylesLoaded[a]=true}}
r(tc,P);c(uc);c(vc);r(tc,wc)}
B();djuqbox.__moduleBase=C();t[S].moduleBase=djuqbox.__moduleBase;var H=F();if(o){var I=!!(o.location.protocol==xc||o.location.protocol==yc);o.__gwt_activeModules[S].canRedirect=I;function J(){var b=zc;try{o.sessionStorage.setItem(b,b);o.sessionStorage.removeItem(b);return true}catch(a){return false}}
if(I&&J()){var K=Ac;var L=o.sessionStorage[K];if(!/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?\/.*$/.test(L)){if(L&&(window.console&&console.log)){console.log(Bc+L)}L=bb}if(L&&!o[K]){o[K]=true;o[K+Cc]=C();var M=p.createElement(jb);M.src=L;var N=p.getElementsByTagName(ob)[V];N.insertBefore(M,N.firstElementChild||N.children[V]);return false}}}G();r(O,wc);A(H);return true}
djuqbox.succeeded=djuqbox();